In [23]:
import numpy as np

In [24]:
a = np.arange(12).reshape(3,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [26]:
for x in np.nditer(a,order= 'C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
for x in np.nditer(a,order= 'F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [28]:
for x in np.nditer(a,order= 'F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [29]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x
    

In [30]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [31]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [33]:
for x,y in np.nditer([a,b]):
    print(x,y)
    

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11
